### ISSUE TITLE
feature request: не проверять class внутри тегов <code>

### ISSUE THREAD

**Issue by nicothin** [DesTincT/bemlint#3]
Ибо дает ложные срабатывания для примеров кода, если в примере есть `class`

**Comment by DesTincT** [comment]
https://github.com/DesTincT/bemlint/commit/6e194a49921a2ca9e66b58bbfe0e1667baec539f

добавил опцию [exclude-selectors](https://github.com/DesTincT/bemlint#options), по дефолту тег  `<code>` включил, хотя конечно индивидуально :)
