### ISSUE TITLE
Ключ --wp не работает?

### ISSUE THREAD

**Issue by nicothin** [DesTincT/bemlint#4]
вызываю `node_modules/.bin/bemlint --elem='__' --mod='--' --wp='[a-z0-9]+(?:-[a-z0-9]+)*' TEMP-html.html `
даже если один из классов написан кириллицей, ошибки нет.

пробую `node_modules/.bin/bemlint --elem='__' --mod='--' --wp='[0-9]+(?:-[0-9]+)*' TEMP-html.html ` — никаких ошибок

этот ключ вообще как-то проверяется? не нашел где именно происходит проверка.

**Comment by DesTincT** [comment]
Да, ключ передаётся в параметр [wordPattern](https://github.com/bem-sdk/bem-naming)

```html
<!-- example.html -->
<div class="b-dropdown">
  <div class="b-dropdown2__element"></div>
</div>
```

`node node_modules/.bin/bemlint --wp='[a-zA-Z0-9]+' example.html`

не выводит ошибок, потомучто класс `b-dropdown` не попадает в паттерн (содержит дефис), и он "пропускается".

Для этого примера всё будет ок:
```html
<!-- example.html -->
<div class="dropdown">
        <div class="dropdown2__element"></div>
</div>
```
```
$ node node_modules/.bin/bemlint --wp='[a-zA-Z0-9]+' example.html

  5:21  warning  Block of the element did not found  isBlockWrapElement

✖ 1 problem (0 errors, 1 warning)
```

`dropdown` попадает в паттерн `[a-zA-Z0-9]+` и для него уже запускается валидация БЭМ

**Comment by nicothin** [comment]
@DesTincT немного неинтуитивно, что `--wp` — это паттерн, определяющий проверять/не_проверять.
Мне казалось, это регулярка, поезволяющая задавать символы, допустимые к использованию в классах...

**Comment by DesTincT** [comment]
> Мне казалось, это регулярка, поезволяющая задавать символы, допустимые к использованию в классах...

не в классах полностью, а только допустимые символы для **блоков**, судя по доке яндекса https://github.com/bem-sdk/bem-naming#custom-naming-convention

в любом случае этот вопрос лучше туда :)
