### ISSUE TITLE
bemlint indexing: crawldb not available, indexing abandoned

### ISSUE THREAD

**Issue by PlanetPush** [DesTincT/bemlint#5]
Hi

I'm having issues with bemlint and Sublimelinter
I have v1.5.0 of bemlint installed globally
I have the latest version of SublimeText (3126)

I see this error in the Sublime console:
TypeError: Cannot read property 'mod' of undefined
at ruleValidator.isRuleOptionsValid (C:\Users\my.name\AppData\Roaming\npm\node_modules\bemlint\lib\rule-validator.js:38:45)
and this:
**indexing: crawldb not available, indexing abandoned**

I have tried uninstalling Sublime, removing bemlint and SublimeLinter packages, restarting Sublime etc but no joy.

The strange thing is that I seem to have just one html file which appears to be getting linted.

Can you help/ advise?
Thanks in advance
James

**Comment by PlanetPush** [comment]
This is an issue for several people in my team. 
However when we revert back to bemlint v1.4.7 it fixes the issue.

v1.5.0 will have been introduced for a reason though so it would be useful to understand why the error was occuring if possible?

Thanks

**Comment by PlanetPush** [comment]
Hmmmm.  I notice that 1.4.7 isn't one of your 'official' tagged releases...
Hey ho.  It works at least!

**Comment by DesTincT** [comment]
thx for review, I will try to figure out the problem

**Comment by DesTincT** [comment]
fixed in v1.5.1, if does not work give me your html code you are trying to lint, please
