### ISSUE TITLE
SublimeText3 (3143) > bemlint v1.6.0 > Cannot read property 'block' of undefined

### ISSUE THREAD

**Issue by PlanetPush** [DesTincT/bemlint#6]
Firstly, thanks for this Plugin.  It's been brilliant.
I've had some issues getting it to work on a new laptop though (i.e. I don't see any warnings for invalid BEM)

In my SublimeText debug console I see the following error:

C:\wamp64\www\node_modules\bemlint\lib\rules.js:54
                if ( currentbemObj && currentbemObj.block == bemObj.block &&
                                                                   ^

TypeError: Cannot read property 'block' of undefined
    at Object.valid (C:\wamp64\www\node_modules\bemlint\lib\rules.js:54:68)

Any ideas?
Thanks
James

**Comment by DesTincT** [comment]
I will try to get into this, give me please your code example with this error

**Comment by PlanetPush** [comment]
I've stripped down the mark-up that was producing this issue.  It is this:

```
<div class="section-3__share-wrapper">
    <div class="section-3__share-btn-list-holder">
      <ul class="share-btn-list">
        <li class="share-btn-list__item"><button class="share share--facebook">Facebook</button></li>
      </ul>
    </div>
</div>  
```

**Comment by DesTincT** [comment]
@PlanetPush update to 1.6.1, it fixes the problem
