### ISSUE TITLE
Как генерировать ошибки, а не предупреждения?

### ISSUE THREAD

**Issue by nicothin** [DesTincT/bemlint#7]
Сейчас после проверок выводятся предупреждения.
Хочется, чтобы генерировались не предупреждения, а ошибки (хочется использовать этот инструмент при автоматической проверке перед коммитом).

**Comment by DesTincT** [comment]
можешь пулл реквест сделать или форк @nicothin https://github.com/DesTincT/bemlint/blob/master/lib/bemlint.js#L109 сюда добавить свойство (message.fatal || message.severity === 2), который включает режим отображения ошибок. Для начала можно просто по флагу `bemlint --errors` логику прокинуть, например.

**Comment by DesTincT** [comment]
вывод настраивается форматтерами в папке formatters, там можно найти использование message.fatal || message.severity

**Comment by DesTincT** [comment]
если супер-гибко, то для каждого правила должно настраиваться отдельно в конфиге, как в еслинте :)

**Comment by DesTincT** [comment]
Готово @nicothin с флагом --errors все сообщения будут ошибками (пока такое быстрое решение)
